import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


/**
 *
 * @author Parker
 */
public class EditAdvert extends javax.swing.JFrame {

    public EditAdvert(int advertID) {
        setTitle("Edit Advertisement");
        initComponents(advertID);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents(int advertID) {

        /*String[] info = Scott.pullEditInfo(advertID)*/

        titleLabel = new javax.swing.JLabel();
        detailLabel = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        titleTextbox = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        detailTextbox = new javax.swing.JTextArea();
        categoryBox = new javax.swing.JComboBox<>();
        priceLabel = new javax.swing.JLabel();
        priceTextbox = new javax.swing.JTextField();
        editAdvertButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setText("Title:");
        titleTextbox.setText(/*info[0]*/String.valueOf(advertID));

        detailLabel.setText("Details:");
        detailTextbox.setColumns(20);
        detailTextbox.setRows(5);
        detailTextbox.setText(/*info[1]*/"");
        jScrollPane1.setViewportView(detailTextbox);

        categoryLabel.setText("Category:");
        categoryBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { /*Scott.getCategories()*/"CAT", "HOU", "ELC", "CCA" }));
        categoryBox.setSelectedItem(/*info[2]*/"CAT");

        priceLabel.setText("Price:");
        priceTextbox.setText(/*info[3]*/"");

        editAdvertButton.setText("Edit Advertisement");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(priceLabel)
                                        .addComponent(categoryLabel)
                                        .addComponent(detailLabel)
                                        .addComponent(titleLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1)
                                        .addComponent(categoryBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(titleTextbox)
                                        .addComponent(editAdvertButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(priceTextbox))
                                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(titleLabel)
                                        .addComponent(titleTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(detailLabel)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(categoryLabel)
                                        .addComponent(categoryBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(priceLabel)
                                        .addComponent(priceTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(editAdvertButton)
                                .addContainerGap(35, Short.MAX_VALUE))
        );

        editAdvertButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String title = titleTextbox.getText();
                String description = detailTextbox.getText();
                String category = (String) categoryBox.getSelectedItem();
                String price = priceTextbox.getText();
                //System.out.println(title + " " + description + " " + category + " " + price);
                /*Scott.editAdvert(title, description, category, price, username)*/
                dispose();
            }
        });

        pack();
    }// </editor-fold>

    // Variables declaration - do not modify
    private javax.swing.JButton editAdvertButton;
    private javax.swing.JComboBox<String> categoryBox;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JLabel detailLabel;
    private javax.swing.JTextArea detailTextbox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField priceTextbox;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField titleTextbox;
    // End of variables declaration
}
